#!/bin/bash

echo "==================================="
echo "CPU/GPU Monitor - Android Project"
echo "==================================="
echo ""
echo "✓ Project Type: Android Application"
echo "✓ Build System: Gradle"
echo "✓ Language: Kotlin"
echo "✓ Min SDK: Android 10 (API 29)"
echo "✓ Target SDK: Android 14 (API 34)"
echo ""
echo "Project Structure:"
echo "==================="
tree -L 3 -I 'build|.gradle|.git' || find . -type f -name "*.kt" -o -name "*.xml" -o -name "*.gradle" | head -20
echo ""
echo "Key Files:"
echo "=========="
echo "✓ build.gradle"
echo "✓ settings.gradle"
echo "✓ app/build.gradle"
echo "✓ MainActivity.kt"
echo "✓ ThermalMonitor.kt"
echo "✓ GitHub Actions workflow"
echo ""
echo "Build Instructions:"
echo "==================="
echo "This Android project requires Android SDK to build locally."
echo ""
echo "To build APK:"
echo "1. Push this code to GitHub"
echo "2. GitHub Actions will automatically build APK"
echo "3. Download APK from Actions tab → Artifacts"
echo ""
echo "Or use tag for automatic release:"
echo "  git tag v1.0.0"
echo "  git push origin v1.0.0"
echo ""
echo "GitHub Actions workflow configured: .github/workflows/build-apk.yml"
echo "==================================="
